<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
    <!-- NuGet restore issue with TargetFrameworks in f# projects: https://github.com/NuGet/Home/issues/10005 -->
    <TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
    <!-- Source-build public sign does not work with F# compiler: https://github.com/dotnet/fsharp/issues/17451 -->
    <SignAssembly Condition="'$(DotNetBuildSourceOnly)' == 'true'">false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CborDocument.fs" />
    <Compile Include="CborPropertyTestContext.fs" />
    <Compile Include="CborDocumentSerializer.fs" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\..\src\System.Formats.Cbor.csproj" />
  </ItemGroup>
</Project>
